FLAGS = -std=c++17 -O3

compiler: lexer.o parser.o flow_graph.o symbol_table.o compiler.o
	$(CXX) $^ -o $@
	strip $@

%.o: %.cpp
	$(CXX) $(FLAGS) -c $^

lexer.cpp: lexer.l parser.h
	flex -o $@ $<

parser.cpp parser.h: parser.y
	bison -Wall -d -o parser.cpp $^

clean:
	rm -f *.o parser.cpp parser.hpp lexer.cpp compiler